#%RAML 1.0 Library
usage: This Library defines the Health Check API.

types:
  healthCheckResponse:
    type: object
    properties:
      timestamp:
        type: string
        required: true
        example: "2019-07-02T12:00:00.000Z"
      status:
        type: string
        required: false
        enum: ["Running", "Down", "Partial"]
        example: "Running"
      details:
        type: object
        required: false
        example: {}

resourceTypes:
  check:
    get:
      description: "Get the system's health"
      responses:
        200:
          body:
            application/json:
              type: healthCheckResponse